server:
  port: 8080
  servlet:
    context-path: /

salesforce:
  oauth:
    client-id: ${SF_CLIENT_ID:你的消费者密钥}
    client-secret: ${SF_CLIENT_SECRET:你的消费者密钥}
    token-url: https://bigdipper-pluto-4490.scratch.my.salesforce.com/services/oauth2/token
    api-version: v59.0

cors:
  allowed-origins:
    - https://bigdipper-pluto-4490.scratch.lightning.force.com/
    - https://bigdipper-pluto-4490.scratch.my.salesforce.com

logging:
  level:
    com.yourpackage: DEBUG
