server:
  port: 8080
  servlet:
    context-path: /

salesforce:
  oauth:
    client-id: 3MVG9xfrbKQ6hByvgri95mPlQsgW0fWHYADXlTzTriHpr7_q_1Gw_GMXTW2v3H2INhcm3wgOvvj2KycUAuqRs
    client-secret: A03F6E80A410765ED16069C81732D01EBAEF4F7C280539A4E6AA41616E188FB1
    token-url: https://bigdipper-pluto-4490.scratch.my.salesforce.com/services/oauth2/token
    api-version: v59.0

cors:
  allowed-origins:
    - https://bigdipper-pluto-4490.scratch.lightning.force.com/
    - https://bigdipper-pluto-4490.scratch.my.salesforce.com

logging:
  level:
    com.yourpackage: DEBUG
  
spring:
  web:
    resources:
      static-locations: classpath:/static/
      
# 禁用X-Frame-Options
  security:
    headers:
      frame: false
