server:
  port: 8080
  servlet:
    context-path: /

salesforce:
  oauth:
    client-id: ${SF_CLIENT_ID}
    client-secret: ${SF_CLIENT_SECRET}
    username: ${SF_USERNAME}
    password: ${SF_PASSWORD}
    ##token-url: https://bigdipper-pluto-4490.scratch.my.salesforce.com/services/oauth2/token
    token-url: ${SF_TOKEN_URL:https://test.salesforce.com/services/oauth2/token}
    api-version: v59.0

cors:
  allowed-origins:
    - https://bigdipper-pluto-4490.scratch.lightning.force.com/
    - https://bigdipper-pluto-4490.scratch.my.salesforce.com

logging:
  level:
    com.yourpackage: DEBUG
  
spring:
  web:
    resources:
      static-locations: classpath:/static/
      
# 禁用X-Frame-Options
  security:
    headers:
      frame: false
